development:
  adapter: postgresql
  encoding: unicode
  database: prowellness_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: prowellness_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: prowellness_production
  pool: 5
  username: prowellness
  password:
